# Generated by Django 2.2.2 on 2019-06-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0002_auto_20190615_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='hotel_list',
            new_name='hotel',
        ),
    ]
